# Survey Propagation at zero temperature

In [5]:
H = readgraph("/tmp/graph9000.txt")
H = readseeds("/tmp/seeds9000.txt", H)
M,N = size(H)

size(H) = (6600, 9000)
5 removed factors [129, 1515, 1531, 1655, 3471]


(6595, 9000)

In [6]:
rowperm,colperm = leaf_removal(H)

([4568, 97, 303, 4962, 589, 3783, 2642, 554, 3162, 1042  …  1081, 4040, 5522, 198, 5901, 3075, 7, 3606, 4236, 3265], [91, 353, 364, 685, 3356, 3896, 4261, 4784, 4976, 5077  …  5628, 7363, 4170, 8751, 4673, 5935, 798, 7435, 4491, 8359])

In [28]:
using StaticArrays, OffsetArrays
x0 = rand((0,1), size(H,2))
s = (-1).^x0;

In [164]:
J = 10
init=OffsetArray(MVector{2J+1}(randn(2J+1)), -J:J)
sp1 = survey_propagation(H; field=s, init, y=2.0);

In [165]:
include("../code/sp.jl")
include("../code/slim_graphs.jl");

In [166]:
b = 20
∂b = nonzeros(sp.X)[nzrange(sp.X, b)]
damp = 0.4
rein = 0.0
sp = deepcopy(sp1)
sp2 = deepcopy(sp1)
e1 = update_factor_zeroT_slow!(sp1, b; damp = 0.0)
e2 = update_factor_zeroT!(sp2, b; damp = 0.0)
[sp1.P[∂b][1] sp2.P[∂b][1]]

J:-1:u = 10:-1:1
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = -0.5878005849657385
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = -0.5878005849657385
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.5224703475356818
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.5224703475356818
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.6003523561989047
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
bnew = [-Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, 2.2490779464214428, -Inf, 0.8705703330180964, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf]
J:-1:u = 10:-1:2
(u, q[u], b[u]) = (2, 0.26401737

J:-1:u = 10:-1:1
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = -0.5878005849657385
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = -0.5878005849657385
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.5224703475356818
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.5224703475356818
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.6003523561989047
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
bnew = [-Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, 2.2490779464214428, -Inf, 0.8705703330180964, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf]
J:-1:u = 10:-1:2
(u, q[u], b[u]) = (2, 0.26401737

J:-1:u = 10:-1:1
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = -0.5878005849657385
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = -0.5878005849657385
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.5224703475356818
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.5224703475356818
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.6003523561989047
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
(u, q[u], b[u]) = (1, -2.4521339537658915, 0.0)
bnew[u] = 0.8705703330180964
bnew = [-Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, 2.2490779464214428, -Inf, 0.8705703330180964, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf, -Inf]
J:-1:u = 10:-1:2
(u, q[u], b[u]) = (2, 0.26401737

21×2 Array{Float64,2}:
 -4.89318  -Inf
 -6.31605  -Inf
 -3.78291  -Inf
 -4.63142  -Inf
 -3.70503  -Inf
 -3.43481  -Inf
 -3.76314  -Inf
 -1.37851  -Inf
 -1.98506  -Inf
 -4.04958  -Inf
 -1.97578    0.0
 -2.67108  -Inf
 -1.67109  -Inf
  0.0      -Inf
 -3.08534  -Inf
 -2.75702  -Inf
 -3.29745  -Inf
 -4.46247  -Inf
 -3.45322  -Inf
 -6.52826  -Inf
 -4.11261  -Inf

In [185]:
Q = [OffsetArray(rand(2J+1),-J:J) for _ in 1:3];

In [187]:
function Bslow(Q)
   b = fill(-Inf, -J:J)
    for hs in Iterators.product(fill(-J:J, length(Q))...)
        u = minimum(abs, hs)
        σ = prod(sign, hs)
        for v in 1:u
           b[v*σ] = max(b[v*σ], sum(q[h] for (q,h) in zip(Q,hs))) 
        end
    end
    b
end

function Bfast(Q)
    b = fill(-Inf, -J:J)
end

Bslow (generic function with 1 method)

In [188]:
Bslow(Q)

21-element OffsetArray(::Array{Float64,1}, -10:10) with eltype Float64 with indices -10:10:
   2.1458679183365446
   2.381715353121411
   2.546931179082812
   2.7361074041509044
   2.7361074041509044
   2.7711358007076043
   2.7711358007076043
   2.8040246449633806
   2.8040246449633806
   2.8040246449633806
 -Inf
   2.807389471851244
   2.807389471851244
   2.807389471851244
   2.774500627595468
   2.774500627595468
   2.6677049047620978
   2.6677049047620978
   2.5411211333308987
   2.375905307369498
   2.375905307369498

In [231]:
function msc_slow(P, J=10, s=1)
    Pnew = copy(P[2:end])
    f = min(-J, sum(firstindex(p) for p in Pnew)+s)
    l = max(J,sum(lastindex(p) for p in Pnew)+s)
    q = fill(Inf, f:l)
    for us in Iterators.product(fill(-J:J, length(Pnew))...)
        h = sum(us) + s
#         @show h
        q[h] = min(q[h],abs(h) - sum(abs.(u)+p[u] for (p,u) in zip(Pnew,us)))
    end
    replace!(q, Inf => -Inf)
    # clamp
    q[J] = maximum(q[J:end])
    q[-J] = maximum(q[begin:-J])
    q[-J:J]
end

function msc_fast(P, J=10, s=1)
    Pnew = [abs.(OffsetArray(-J:J, -J:J)) + p for p in P[2:end]]
    f = fill(0.0, s:s)
    for n in eachindex(Pnew)
        f = msc(f, Pnew[n])
    end  
    q = fill(-Inf, -J:J)
    for h in eachindex(f)
        q[clamp(h,-J,J)] = max(q[clamp(h,-J,J)], abs(h) - f[h])
    end
        @show q_fast=q
    q  
end
    
function msc_faster(P, J=10, s=1)
    Pnew = [abs.(OffsetArray(-J:J, -J:J)) + p for p in P[2:end]]
    init = fill(0.0, s:s)
    Q = [fill(0.0, 0:0) for a ∈ 1:length(Pnew)]
    f = cavity!(Q, Pnew, msc, init)
    q = fill(-Inf, -J:J)
    for h in eachindex(f)
        q[clamp(h,-J,J)] = max(q[clamp(h,-J,J)], abs(h) - f[h])
    end
    @show q_faster = q
    q
end

msc_faster (generic function with 3 methods)

In [136]:
i = 2
∂i = nzrange(sp.H, i)
damp = 0.0
rein = 0.0
sp = deepcopy(sp1)
e1 = update_var_zeroT_slow!(sp1, i; damp = damp, rein = 0.0)
e2 = update_var_zeroT!(sp, i; damp = damp, rein = 0.0)
[sp1.survey[i] sp.survey[i]]
[sp1.Q[∂i][2] sp.Q[∂i][2]]
e1,e2

(6.223191904617884, 6.223191904617884)

In [242]:
Pnew = vcat(sp.P[∂i],copy(sp.P[∂i])) 

4-element Array{OffsetArray{Float64,1,Array{Float64,1}},1}:
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [244]:
s = sp.efield[i]
ff = msc_faster(Pnew,J,s)
fa = msc_fast(Pnew,J,s)
ff == fa

q_faster = q = [1.0, -19.0, -19.0, -19.0, -19.0, -19.0, -19.0, -19.0, -19.0, -19.0, -21.0, -21.0, -21.0, -21.0, -21.0, -21.0, -21.0, -21.0, -21.0, -21.0, -1.0]
q_fast = q = [1.0, -19.0, -19.0, -19.0, -19.0, -19.0, -19.0, -19.0, -19.0, -19.0, -21.0, -21.0, -21.0, -21.0, -21.0, -21.0, -21.0, -21.0, -21.0, -21.0, -1.0]


true

In [254]:
J = sp.J
∂i = nzrange(sp.H, i)
# P = [OffsetArray(rand(2J+1), -J:J) for _ in 1:5]
s = sp.efield[i]
sl = msc_slow(P,J,s)
fa = msc_fast(P,J,s)
ff = msc_faster(P,J,s)
[sl fa ff]

q_fast = q = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -Inf]
q_faster = q = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -Inf]


21×3 Array{Float64,2}:
   1.0    1.0    1.0
   1.0    1.0    1.0
   1.0    1.0    1.0
   1.0    1.0    1.0
   1.0    1.0    1.0
   1.0    1.0    1.0
   1.0    1.0    1.0
   1.0    1.0    1.0
   1.0    1.0    1.0
   1.0    1.0    1.0
  -1.0   -1.0   -1.0
  -1.0   -1.0   -1.0
  -1.0   -1.0   -1.0
  -1.0   -1.0   -1.0
  -1.0   -1.0   -1.0
  -1.0   -1.0   -1.0
  -1.0   -1.0   -1.0
  -1.0   -1.0   -1.0
  -1.0   -1.0   -1.0
  -1.0   -1.0   -1.0
 -Inf   -Inf   -Inf

In [201]:
s = 1
f1 = OffsetArray(randn(2J+1), -J:J)
f2 = OffsetArray(randn(2J+1), -J:J)
init = fill(0.0, s:s)
g1 = msc(f1, msc(f2,init))
g2 = cavity!([f1,f2], [f1,f2], msc, init)
g2==g1

true